- name: Provision Docker containers
  hosts: localhost
  tasks:
    - name: Start ubuntu containers
      docker_container:
         image: tektutor/ansible-ubuntu
         name: "ubuntu{{item}}"
         state: present
         ports:
           - "200{{item}}:22"
           - "800{{item}}:80"
      with_sequence: start=1 end=2
         
    - name: Start centos containers
      docker_container:
         image: tektutor/ansible-centos
         name: "centos{{item}}"
         state: present
         ports:
           - "300{{item}}:22"
           - "900{{item}}:80"
      with_sequence: start=1 end=2
